### ISSUE TITLE
Tlm Packets error

### ISSUE THREAD

**Issue by kihwankim** [OpenSatKit/OpenSatKit#35]
Hi! I followed this video (https://www.youtube.com/watch?v=LspTUdIKAZY&t=36s)

when I click here
![화면](https://user-images.githubusercontent.com/19687080/87001195-d4d17f80-c1f1-11ea-9d88-62b31124d4ed.PNG)

and

![error 표시](https://user-images.githubusercontent.com/19687080/87001247-f3d01180-c1f1-11ea-8a78-ca2153a9a065.PNG)

and this is my cMake and cpu1_cfe_es_startup.scr

![cpu1_cfe_es_startupscrerror](https://user-images.githubusercontent.com/19687080/87001292-1530fd80-c1f2-11ea-9971-eb936d38f8ea.png)

I can not find why it happened

**Comment by dmccomas** [comment]
Thanks for the details, they're very helpful.

It looks like the file ~/cosmos/config/tools/cmd_tlm_server/
cmd_tlm_server.txt was not automatically updated.  The tool should have
inserted a line
"TARGET EXAMPLE" between the   <cfs_kit> and ,</cfs_kit> tags.  Hopefully
the following steps will fix the problem:

1. Add a "TARGET EXAMPLE" line to the list of targets under the "INTERFACE
LOCAL_CFS_INT udp_cs_interface.rb 127.0.0.1 1234 1235 nil nil 128 nil nil".
Between the <cfs_kit> tags is fine.
2. Restart COSMOS.

Is anything between the  <cfs_kit>  tags? I'm wondering what happened.

Thanks - Dave

**Comment by kihwankim** [comment]
thank you for your answer.
![3](https://user-images.githubusercontent.com/19687080/87261790-9211ef00-c4f2-11ea-9490-b683255e4f8e.PNG)

but there's another problem.
![1](https://user-images.githubusercontent.com/19687080/87261796-95a57600-c4f2-11ea-8d78-65bbf41634cd.PNG)
![2](https://user-images.githubusercontent.com/19687080/87261802-96d6a300-c4f2-11ea-9c14-0b46d3fe8085.PNG)

I opened like this but It said the pakcet has never come. so I wonder what's wrong is there and if there is any other data needed to analyze the problem, I will upload the photo or log again.

thank you

**Comment by kihwankim** [comment]
and Stop cFS/Server is not working 

![4](https://user-images.githubusercontent.com/19687080/87261934-1e241680-c4f3-11ea-84d8-885708754079.PNG)

in this page

thank you!!

**Comment by ArrobaRicardoGE** [comment]
@kihwankim Were you able to solve the problem of the missing packet? I am having a similar poblem.

**Comment by dmccomas** [comment]
Sorry this dropped off the radar.  Its confusing because EXAMPLE is showing up as an available target but the error states its not a target. I've tried a lot of permutations of things that may hav egone wrong during the automated process but I can't reporduce the issue. Can you please attach the exception log, hopefully some clues.

**Comment by dmccomas** [comment]
I get the same error if the COSMOS Command and Telemetry Server is not restarted after the EXAMPLE code is generated.  It could be a problem with the script that runs when button 4 (Stop cFS/Server) is pressed.  

You can manually close the GUI titled "cFS Command and Telemetry Server" and on the COSMOS launcher start the server back up by selecting the "Command and Telemetry Server" button.  See pic although the button order has changed in later releases. Select 'OK' on the pop up that asks about 'cmd_tlm_server.txt'.  

If you have shut everthing down since first generating the code the probelm should not have persist when you restart OSK.  If it does then we have another problem.  

![ScreenHunter 88](https://user-images.githubusercontent.com/1598728/108633291-7b952400-7441-11eb-88e6-93abfb8477d2.png)
